### ISSUE TITLE
Fatal PHP error

### ISSUE THREAD

**Issue by timbowen** [xwp/site-performance-tracker#14]
When activating the plugin I get these errors:

```
Fatal error: Uncaught Error: Class 'Site_Performance_Tracker\Plugin' not found in /app/public/wp-content/plugins/site-performance-tracker-master/site-performance-tracker.php on line 60

Error: Class 'Site_Performance_Tracker\Plugin' not found in /app/public/wp-content/plugins/site-performance-tracker-master/site-performance-tracker.php on line 60
```

Let me know if I can help troubleshoot.

**Comment by delawski** [comment]
@timbowen The plugin is meant to be installed as a Composer dependency. We're currently updating the readme file so that it includes the instructions. Here's a direct link to the Installation section:

https://github.com/xwp/site-performance-tracker/blob/f3e56172f905a340be7d5da85b4c5157f54ce999/README.md#installation

**Comment by kasparsd** [comment]
@timbowen Sorry for the confusion around this. I'll open an issue for creating distribution zips (that contain the autoloader) that are added to every release.
