### ISSUE TITLE
Support for Web Vitals

### ISSUE THREAD

**Issue by kasparsd** [xwp/site-performance-tracker#22]
Add support for tracking [Web Vitals](https://web.dev/vitals/).

**Comment by mehigh** [comment]
By providing an feature for
https://github.com/GoogleChrome/web-vitals/
We would be able to gather RUM data immediately post-deployment in Google Analytics rather than wait 28 days for GSC data to refresh

This particular feature only as a dependency for Google Analytics, and due to the availability of buffering for performance observer entering https://www.chromestatus.com/feature/5118272741572608 the metrics before the monitoring code is run would also be made available, hence this can be delayed to run much later when the CPU is idling.
https://github.com/GoogleChromeLabs/web-vitals-report/blob/71b0879334798c732f460945ded5267cab5a36bf/src/js/analytics.js#L135
